// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4b7BhfifALx5D7LsgHxXKMYlnu1xcpaU',
    appId: '1:1023679998285:web:9bd3f111d5c627aa7bef04',
    messagingSenderId: '1023679998285',
    projectId: 'freelanser-24cb4',
    authDomain: 'freelanser-24cb4.firebaseapp.com',
    storageBucket: 'freelanser-24cb4.firebasestorage.app',
    measurementId: 'G-WM3G9BKDWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNicGuzo_CedB7jLmLB2R2I3I2PKqxvA',
    appId: '1:1023679998285:android:0a367ba00d172eb87bef04',
    messagingSenderId: '1023679998285',
    projectId: 'freelanser-24cb4',
    storageBucket: 'freelanser-24cb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZUH54lfdd76NTzq_HQOYxyE_H5KWCJI',
    appId: '1:1023679998285:ios:6a12680260bf6c637bef04',
    messagingSenderId: '1023679998285',
    projectId: 'freelanser-24cb4',
    storageBucket: 'freelanser-24cb4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlZUH54lfdd76NTzq_HQOYxyE_H5KWCJI',
    appId: '1:1023679998285:ios:6a12680260bf6c637bef04',
    messagingSenderId: '1023679998285',
    projectId: 'freelanser-24cb4',
    storageBucket: 'freelanser-24cb4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
